Blind merge with upstream! verification of changes is required in pycbc/events/stat.py, bin/plotting/pycbc_plot_vt_ratio; scripts in bin/hdfcoinc to be moved and merged with resp ones in bin/all_sky_search

diff --git a/bin/pycbc_submit_dax b/bin/pycbc_submit_dax
--- a/bin/pycbc_submit_dax
+++ b/bin/pycbc_submit_dax
@@ -29,8 +29,10 @@ TRANSFORMATION_CATALOG=""
 LOCAL_STAGING_SERVER="file://"
 REMOTE_STAGING_SERVER=""
 NO_CREATE_PROXY=0
+NO_QUERY_DB=0
 NO_GRID=""
 SUBMIT_DAX="--submit"
+HTML_ENTITIES="{\"\'\": '&#39;', '(': '&#40;', ')': '&#41;', '+': '&#43;', '\"': '&quot;'}"
 
 # These will be changed by the bundle builder
 DATA_INLINE=False
@@ -48,7 +50,7 @@ rm -f _reuse.cache
 touch _reuse.cache
 rm -f *-extra-site-properties.xml
 
-GETOPT_CMD=`getopt -o d:c:g:r:a:u:p:P:es:S:k:t:Fknl:Gh --long dax:,cache-file:,local-staging-server:,remote-staging-server:,accounting-group:,accounting-group-user:,pegasus-properties:,append-pegasus-property:,enable-shared-filesystem,execution-sites:,staging-sites:,append-site-profile:,transformation-catalog:,force-no-accounting-group,no-create-proxy,no-submit,local-dir:,no-grid,help -n 'pycbc_submit_dax' -- "$@"`
+GETOPT_CMD=`getopt -o d:c:g:r:a:u:p:P:es:S:k:t:Fknl:Gh --long dax:,cache-file:,local-staging-server:,remote-staging-server:,accounting-group:,accounting-group-user:,pegasus-properties:,append-pegasus-property:,enable-shared-filesystem,execution-sites:,staging-sites:,append-site-profile:,transformation-catalog:,force-no-accounting-group,no-create-proxy,no-query-db,no-submit,local-dir:,no-grid,help -n 'pycbc_submit_dax' -- "$@"`
 eval set -- "$GETOPT_CMD"
 
 while true ; do
@@ -73,9 +75,18 @@ while true ; do
                  cat ${FILE_URL} >> _reuse.cache
                  FOUND_URL=0
               else
-                 # otherwise try and get the file using curl
-                 curl --fail ${URL} >> _reuse.cache
+                 # otherwise try and get the file using resolve_url
+                 DOWNLOADED_FILE=`python - <<EOF
+from pycbc.workflow import resolve_url
+import os
+filename = resolve_url("${FILE_URL}")
+print(filename)
+EOF`
                  FOUND_URL=${?}
+                 if [ ${FOUND_URL} -eq 0 ] ; then
+                   cat $DOWNLOADED_FILE >> _reuse.cache
+                   rm -f $DOWNLOADED_FILE
+                 fi
               fi
               if [ ${FOUND_URL} -ne 0 ] ; then
                  echo "$URL not found!"
@@ -131,7 +142,7 @@ while true ; do
       case "$2" in
         "") shift 2 ;;
         *) SITE_PROFILE=${2}
-           APPEND_SITE_PROFILE_ARRAY=`perl -e 'use HTML::Entities; print encode_entities(decode_entities(<STDIN>), "\'\"'\'\''<>()&+" );' <<< ${SITE_PROFILE}`
+           APPEND_SITE_PROFILE_ARRAY=$(python -c "import sys; from xml.sax.saxutils import (escape, unescape); print(escape(unescape(sys.stdin.read()), entities=${HTML_ENTITIES}))" <<< ${SITE_PROFILE})
            OIFS=${IFS}; IFS=":"
            read -ra APPEND_SITE_PROFILE_ARRAY <<< "${APPEND_SITE_PROFILE_ARRAY}"
            IFS=${OIFS}
@@ -157,6 +168,7 @@ while true ; do
       esac ;;
     -F|--force-no-accounting-group) NO_ACCOUNTING_GROUP=1 ; shift ;;
     -K|--no-create-proxy) NO_CREATE_PROXY=1 ; shift ;;
+    -Q|--no-query-db) NO_QUERY_DB=1 ; shift ;;
     -n|--no-submit) SUBMIT_DAX="" ; shift ;;
     -l|--local-dir)
       case "$2" in
@@ -444,13 +456,13 @@ echo
 rm -f submitdir
 ln -sf $SUBMIT_DIR submitdir
 
-echo pegasus-status --verbose --long $SUBMIT_DIR/work > status
+echo "pegasus-status --verbose --long $SUBMIT_DIR/work \$@" > status
 chmod 755 status
 
-echo pegasus-analyzer -r -v $SUBMIT_DIR/work > debug
+echo "pegasus-analyzer -r -v $SUBMIT_DIR/work \$@" > debug
 chmod 755 debug
 
-echo pegasus-remove $SUBMIT_DIR/work > stop
+echo "pegasus-remove $SUBMIT_DIR/work \$@" > stop
 chmod 755 stop
 
 if [ -z "${NO_GRID}" ] ; then
@@ -489,7 +501,7 @@ fi
 EOF
 fi
 
-echo pegasus-run $SUBMIT_DIR/work > start
+echo "pegasus-run $SUBMIT_DIR/work \$@" > start
 
 chmod 755 start
 
@@ -550,48 +562,52 @@ set +e
 condor_reschedule &> /dev/null
 set -e
 
-/bin/echo "Querying Pegasus database for workflow stored in ${SUBMIT_DIR}/work"
-/bin/echo -n "This may take up to 120 seconds. Please wait..."
-rm -f pegasus_db.log
-touch pegasus_db.log
-# querying the database sometimes fails, so allow retries
-set +e
-until [ $DB_TRY -ge 15 ]
-do
-  /bin/echo -n "."
-  WORKFLOW_ID_STRING=`eval $WORKFLOW_DB_CMD 2>> pegasus_db.log`
-  if [ $? -eq 0 ] && [ ! -z $WORKFLOW_ID_STRING ] ; then
-    /bin/echo " Done."
-    DB_QUERY_SUCCESS=0
-    break
-  else
-    DB_QUERY_SUCCESS=1
-  fi
-  DB_TRY=$(( $DB_TRY + 1 ))
-  for s in `seq ${DB_TRY}`
-  do
-    /bin/echo -n "."
-    sleep 1
-  done
-done
-set -e
+if [ $NO_QUERY_DB == 0 ]; then
 
-if [ ${DB_QUERY_SUCCESS} -eq 1 ] ; then
-  echo; echo
-  /bin/echo "Query failed: ${WORKFLOW_DB_CMD}"
-  cat pegasus_db.log
-else
-  rm -f pegasus_db.log
-fi
+    /bin/echo "Querying Pegasus database for workflow stored in ${SUBMIT_DIR}/work"
+    /bin/echo -n "This may take up to 120 seconds. Please wait..."
+    rm -f pegasus_db.log
+    touch pegasus_db.log
+    # querying the database sometimes fails, so allow retries
+    set +e
+    until [ $DB_TRY -ge 15 ]
+    do
+      /bin/echo -n "."
+      WORKFLOW_ID_STRING=`eval $WORKFLOW_DB_CMD 2>> pegasus_db.log`
+      if [ $? -eq 0 ] && [ ! -z $WORKFLOW_ID_STRING ] ; then
+        /bin/echo " Done."
+        DB_QUERY_SUCCESS=0
+        break
+      else
+        DB_QUERY_SUCCESS=1
+      fi
+      DB_TRY=$(( $DB_TRY + 1 ))
+      for s in `seq ${DB_TRY}`
+      do
+        /bin/echo -n "."
+        sleep 1
+      done
+    done
+    set -e
 
-if [ -z $WORKFLOW_ID_STRING ] ; then
-  echo "WARNING: Could not find the workflow in the Pegasus dashboard database."
-  echo "         Workflow has been submitted but the results page will not contain"
-  echo "         a link to the dashboard page. If this is a production workflow,"
-  echo "         please remove the workflow, check for the origin of this error,"
-  echo "         and re-submit the workflow by re-running this script."
-  echo
-  exit 1
+    if [ ${DB_QUERY_SUCCESS} -eq 1 ] ; then
+      echo; echo
+      /bin/echo "Query failed: ${WORKFLOW_DB_CMD}"
+      cat pegasus_db.log
+    else
+      rm -f pegasus_db.log
+    fi
+
+    if [ -z $WORKFLOW_ID_STRING ] ; then
+      echo "WARNING: Could not find the workflow in the Pegasus dashboard database."
+      echo "         Workflow has been submitted but the results page will not contain"
+      echo "         a link to the dashboard page. If this is a production workflow,"
+      echo "         please remove the workflow, check for the origin of this error,"
+      echo "         and re-submit the workflow by re-running this script."
+      echo
+      exit 1
+    fi
+
 fi
 
 WORKFLOW_ID_ARRAY=(${WORKFLOW_ID_STRING//,/ })
@@ -610,9 +626,9 @@ if [ -e ${DASHBOARD_PATH} ] ; then
     cp ${DASHBOARD_PATH} ${DASHBOARD_COPY}
   fi
 
-  COMMAND_LINE=`perl -e 'use HTML::Entities; print encode_entities(decode_entities(<STDIN>), "\'\"'\'\''<>()&+" );' <<< ${COMMAND_LINE}`
-  perl -pi.bak -e "s+PYCBC_SUBMIT_DAX_ARGV+${COMMAND_LINE}+g" ${DASHBOARD_PATH}
-  perl -pi.bak -e "s+PEGASUS_DASHBOARD_URL+${DASHBOARD_URL}+g" ${DASHBOARD_PATH}
+  COMMAND_LINE=$(python -c "import sys; from xml.sax.saxutils import (escape, unescape); print(escape(unescape(sys.stdin.read()), entities=${HTML_ENTITIES}))" <<< ${SITE_PROFILE})
+  sed -i.bak -e "s+PYCBC_SUBMIT_DAX_ARGV+${COMMAND_LINE}+g" ${DASHBOARD_PATH}
+  sed -i.bak -e "s+PEGASUS_DASHBOARD_URL+${DASHBOARD_URL}+g" ${DASHBOARD_PATH}
 fi
 shopt -u nullglob
 
